apiVersion: v1
kind: Service
metadata:
  name: magic-tavern-backend
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: magic-tavern-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.containerPort }}
      nodePort: {{ .Values.backend.nodePort }}
