apiVersion: v1
kind: Service
metadata:
  name: magic-tavern-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: magic-tavern-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.nodePort }}
