apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: magic-tavern-infisical-connection
  namespace: {{ .Values.namespace }}
spec:
  address: {{ .Values.infisical.connectionAddress }}
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: magic-tavern-k8s-operator-auth
  namespace: {{ .Values.namespace }}
spec:
  infisicalConnectionRef:
    name: magic-tavern-infisical-connection
    namespace: {{ .Values.namespace }}
  method: universal
  universal:
    clientIdRef:
      name: {{ .Values.infisical.machineIdentitySecretName }}
      namespace: {{ .Values.namespace }}
      key: clientId
    clientSecretRef:
      name: {{ .Values.infisical.machineIdentitySecretName }}
      namespace: {{ .Values.namespace }}
      key: clientSecret
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: magic-tavern-backend-secret-sync
  namespace: {{ .Values.namespace }}
spec:
  infisicalAuthRef:
    name: magic-tavern-k8s-operator-auth
    namespace: {{ .Values.namespace }}
  sources:
    - projectId: {{ .Values.infisical.projectId | quote }}
      environmentSlug: {{ .Values.infisical.environmentSlug }}
      secretPath: /
  targets:
    - name: {{ .Values.backend.secretName }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Owner
      secretType: Opaque
  syncOptions:
    refreshInterval: 60s
    instantUpdates: true
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: magic-tavern-ghcr-secret-sync
  namespace: {{ .Values.namespace }}
spec:
  infisicalAuthRef:
    name: magic-tavern-k8s-operator-auth
    namespace: {{ .Values.namespace }}
  sources:
    - projectId: {{ .Values.infisical.projectId | quote }}
      environmentSlug: {{ .Values.infisical.environmentSlug }}
      secretPath: /
  targets:
    - name: {{ .Values.imagePullSecret }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Owner
      secretType: kubernetes.io/dockerconfigjson
      template:
        engineVersion: v1
        data:
          .dockerconfigjson: |-
            {{`{{- $hostname := "ghcr.io" -}}`}}
            {{`{{- $config := dict "auth" (list "joncax" ":" .NERV_GHCR_PUSH.Value | join "" | b64enc) -}}`}}
            {{`{{- dict "auths" (dict $hostname $config) | mustToJson -}}`}}
  syncOptions:
    refreshInterval: 60s
    instantUpdates: true
