apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerv-pantry-frontend
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: nerv-pantry-frontend
  template:
    metadata:
      labels:
        app: nerv-pantry-frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
