namespace: nerv-pantry
imagePullSecret: ghcr-secret

backend:
  image:
    repository: ghcr.io/joncax/nerv-pantry-backend
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  containerPort: 8000
  nodePort: 30191
  secretName: nerv-pantry-backend-secret
  env:
    postgresHost: nerv-pantry-postgres
    postgresPort: "5432"
    postgresDb: nerv_pantry
    postgresUser: pantry_user
    imagesPath: /data/images
    appVersion: "1.0.0"
    debug: "false"
    offApiUrl: "https://world.openfoodfacts.org/api/v2"

frontend:
  image:
    repository: ghcr.io/joncax/nerv-pantry-frontend
    tag: latest
    pullPolicy: IfNotPresent
  port: 80
  containerPort: 80
  nodePort: 30190

postgres:
  image: postgres:16-alpine
  port: 5432
  storage: 2Gi
  pvcName: postgres-pvc

images:
  storage: 5Gi
  pvcName: images-pvc
